from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from rich.text import Text
from rich import box

console = Console()

# 🌟 Header with gradient style
def print_header():
    title = Text("🤖 AI MULTI-AGENT RAG SYSTEM", style="bold white on blue")
    subtitle = Text("Powered by LangGraph + Gemini + ChromaDB", style="bold magenta")

    console.print("\n")
    console.print(Panel(title, expand=False, box=box.DOUBLE))
    console.print(subtitle)
    console.print("\n")


# 🧑 User query (highlighted neon style)
def print_query(query: str):
    console.print(
        Panel.fit(
            f"[bold yellow]🧑 You asked:[/bold yellow]\n\n[white]{query}[/white]",
            border_style="green",
            box=box.ROUNDED
        )
    )


# 📋 Plan (blue cyber style)
def print_plan(plan: str):
    console.print(
        Panel(
            Markdown(plan),
            title="📋 PLANNING AGENT",
            border_style="cyan",
            box=box.DOUBLE_EDGE
        )
    )


# 🔍 Research (yellow/orange energy)
def print_research(research: str):
    console.print(
        Panel(
            Markdown(research),
            title="🔍 RESEARCH AGENT",
            border_style="yellow",
            box=box.ROUNDED
        )
    )


# ✍️ Final answer (premium purple look)
def print_final(output: str):
    console.print(
        Panel(
            Markdown(output),
            title="📄 FINAL ANSWER",
            border_style="magenta",
            box=box.DOUBLE,
            subtitle="✨ Generated by AI Agents"
        )
    )